### ISSUE TITLE
A question about the Graphics Card used for training.

### ISSUE THREAD

**Issue by M0NSTERCOCO** [yinjunbo/IS-Fusion#13]
Hi, thank you for your great work!
May I ask what graphics card you used to train the model? Our lab has eight 3080 graphics cards with 10G of memory, is that enough to support training? Thanks!

**Comment by yinjunbo** [comment]
Hi, thanks for your interest. With low-memory GPUs, you can try to reduce batch size to 1 to run the model. However, this might cause a performance drop.
