### ISSUE TITLE
train 

### ISSUE THREAD

**Issue by sidiangongyuan** [yinjunbo/IS-Fusion#14]
When I want to train, I need to use the pre-trained parameters of the image backbone you provided. So I can train IS-Fusion directly, right?

**Comment by yinjunbo** [comment]
Yes. You should specify the location of the pretrained model in this line to start the training of IS-Fusion.
https://github.com/yinjunbo/IS-Fusion/blob/167dc78de50da583a87597d57791f3dcbca91e9b/configs/isfusion/isfusion_0075voxel.py#L433

**Comment by sidiangongyuan** [comment]
OK ， tk

**Comment by rubbish001** [comment]
兄弟，你复现了他的精度吗
