### ISSUE TITLE
No module named 'mmdet3d.models.detectors.centerpoint_fusion',Missing centerpoint_fusion, centerpoint_dv, dynamic_voxelnet_img

### ISSUE THREAD

**Issue by 916769467** [yinjunbo/IS-Fusion#15]
Hello，Thank you for sharing code！I try to run "test.py"，but the error prompt is "No module named 'mmdet3d.models.detectors.centerpoint_fusion' " ,I try to find the github of mmdet3d,but I can't find the centerpoint_fusion.py ,centerpoint_dv.py, dynamic_voxelnet_img.py. How can I do to run the code?Thx!

**Comment by yinjunbo** [comment]
These files are in AutoAlignV2. You can use the updated __init__ file to run the code. Thx.
https://github.com/yinjunbo/IS-Fusion/blob/3f4cb939033a08be5e0f35d8d47dbb32895edda2/mmdet3d/models/detectors/__init__.py#L20

**Comment by 916769467** [comment]
I see!Anthor question，the path: IS-Fusion-master/mmdet3d/ops/voxel/voxelize.py:line 7->from .voxel_layer import dynamic_voxelize, hard_voxelize   ;At the beginning，it prompt "No module named voxel_layer"，I find the project ,but i can't find the voxel_layer.py.Then I download the mmdet3d-1.6.0 and "python setup.py install". I copy "mmdetection3d-0.16.0/build/lib.linux-x86_64-3.8/mmdet3d/ops/voxel/voxel_layer.cpython-38-x86_64-linux-gnu.so" to "IS-Fusion-master/mmdet3d/ops/voxel/".The error becomes normal.And combining the above you answer，the code can run,bun it down at voxelize.py(line 62)->"voxel_num = hard_voxelize(...)"，I suspect that the "voxel_layer.cpython-38-x86_64-linux-gnu.so" what I copy is wrong.How can I get the voxel_layer.py?Thx!

**Comment by 916769467** [comment]
In addition,My pip list version:
mmcv-full                            1.4.0
mmdet                                2.14.0
mmdet3d                              0.16.0
mmsegmentation                       0.14.1
torch                                1.10.0+cu113

**Comment by 916769467** [comment]
Thx!I can run the test.py code and see the result(I debug the function of lib because of the different version)!Thank you for your great work!

**Comment by 916769467** [comment]
Thx!I can run the test.py code and see the result(I debug the function of lib because of the different version)!Thank you for your great work!

**Comment by yinjunbo** [comment]
Happy to hear that. Thank you.
