### ISSUE TITLE
When using the provided model for validation, the model dimensions and configuration file do not match

### ISSUE THREAD

**Issue by yuezhao1** [yinjunbo/IS-Fusion#18]
When I use the model you provided, download it from https://drive.google.com/file/d/1mY2juJ2n0Dw5NWDSraZXrdU1RwkE-40h/view?usp=sharing
Use Command
python tools/test.py configs/isfusion/isfusion_0075voxel.py data/pretrain_models/IS-Fusion_epoch_10.pth --eval "mAP" "NDS"

The part about pts_middle_decoder in my configuration file has not been changed：

    pts_middle_encoder=dict(
        type='SparseEncoder',
        in_channels=64,
        sparse_shape=[41, voxel_shape, voxel_shape],
        base_channels=32,
        output_channels=256,
        order=('conv', 'norm', 'act'),
        encoder_channels=((32, 32, 64), (64, 64, 128), (128, 128, 256), (256, 256)),
        encoder_paddings=((0, 0, 1), (0, 0, 1), (0, 0, [0, 1, 1]), (0, 0)),
        block_type='basicblock',
    ),

The error logs are as follows：

load checkpoint from local path: data/pretrain_models/IS-Fusion_epoch_10.pth
The model and loaded state dict do not match exactly

size mismatch for pts_middle_encoder.conv_input.0.weight: copying a param with shape torch.Size([32, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.0.conv1.weight: copying a param with shape torch.Size([32, 3, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 32, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.0.conv2.weight: copying a param with shape torch.Size([32, 3, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 32, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.1.conv1.weight: copying a param with shape torch.Size([32, 3, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 32, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.1.conv2.weight: copying a param with shape torch.Size([32, 3, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 32, 32]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer1.2.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 32]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 32, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.0.conv1.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.0.conv2.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.1.conv1.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.1.conv2.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer2.2.0.weight: copying a param with shape torch.Size([128, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 128]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.0.conv1.weight: copying a param with shape torch.Size([128, 3, 3, 3, 128]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 128, 128]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.0.conv2.weight: copying a param with shape torch.Size([128, 3, 3, 3, 128]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 128, 128]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.1.conv1.weight: copying a param with shape torch.Size([128, 3, 3, 3, 128]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 128, 128]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.1.conv2.weight: copying a param with shape torch.Size([128, 3, 3, 3, 128]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 128, 128]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer3.2.0.weight: copying a param with shape torch.Size([256, 3, 3, 3, 128]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 128, 256]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer4.0.conv1.weight: copying a param with shape torch.Size([256, 3, 3, 3, 256]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 256, 256]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer4.0.conv2.weight: copying a param with shape torch.Size([256, 3, 3, 3, 256]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 256, 256]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer4.1.conv1.weight: copying a param with shape torch.Size([256, 3, 3, 3, 256]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 256, 256]).
size mismatch for pts_middle_encoder.encoder_layers.encoder_layer4.1.conv2.weight: copying a param with shape torch.Size([256, 3, 3, 3, 256]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 256, 256]).
size mismatch for pts_middle_encoder.conv_out.0.weight: copying a param with shape torch.Size([256, 3, 1, 1, 256]) from checkpoint, the shape in current model is torch.Size([3, 1, 1, 256, 256]).
/home/user/miniconda3/envs/IS-Fusion/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load checkpoint from local path: data/pretrain_models/IS-Fusion_epoch_10.pth
......................

And only the dimensions of pts_middle_decoder do not match.

May I ask if it's an error in my configuration file or the model file I downloaded from Google Drive?

Thank you

**Comment by yinjunbo** [comment]
You might try to modify the command as `python tools/test.py configs/isfusion/isfusion_0075voxel.py data/pretrain_models/IS-Fusion_epoch_10.pth --eval bbox`

**Comment by yuezhao1** [comment]
After changing the mode of eval in the command to bbox, the error still exists. This seems to be due to the different order of feature dimensions between the model and configuration file in the pts_middle_decoder section.Will the order of this dimension be affected by the eval mode?
I feel like it's because there's a problem with my model or configuration file.
@yinjunbo

**Comment by yinjunbo** [comment]
Yes, there is a version mismatch of the sparseconv lib. Please make sure
use the correct version and corresponding codes.

**Comment by loserhou** [comment]
> You are right, I found that spconv is not installed in my environment. After installing the corresponding spconv according to my CUDA version, the problem of model dimension mismatch disappeared. Thank you very much. @yinjunbo

老哥请问你配置环境的时候clone完mmdetection3d后需要用作者给的mmdet3d覆盖吗？

**Comment by yuezhao1** [comment]
> > You are right, I found that spconv is not installed in my environment. After installing the corresponding spconv according to my CUDA version, the problem of model dimension mismatch disappeared. Thank you very much. @yinjunbo
> 
> 老哥请问你配置环境的时候clone完mmdetection3d后需要用作者给的mmdet3d覆盖吗？

什么意思，我记得clone完，pip install -v -e .好像就可以，按作者给的步骤应该就没问题

**Comment by loserhou** [comment]
搞定了，谢谢！还想问下你复现的时候可以达到作者的精度吗？我这边资源有限，如果能达到的话我就不训练了。






| |
侯业飞
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 7/24/2024 13:34 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [yinjunbo/IS-Fusion] When using the provided model for validation, the model dimensions and configuration file do not match (Issue #18) |

You are right, I found that spconv is not installed in my environment. After installing the corresponding spconv according to my CUDA version, the problem of model dimension mismatch disappeared. Thank you very much. @yinjunbo

老哥请问你配置环境的时候clone完mmdetection3d后需要用作者给的mmdet3d覆盖吗？

什么意思，我记得clone完，pip install -v -e .好像就可以，按作者给的步骤应该就没问题

**Comment by yuezhao1** [comment]
我也只是测试了他给的模型，map是0.7250，NDS是0.7365 @loserhou
