### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by loserhou** [yinjunbo/IS-Fusion#19]
when i run  python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0
i found a strange bug
![0206f4b955858c715d4437c408a32d0](https://github.com/user-attachments/assets/c19da6ee-5fe2-4a12-8f58-9b85789047a9)
could you give me some advice?

**Comment by loserhou** [comment]
the create_groundtruth_database() have the argument with_bbox

**Comment by LxxxxK** [comment]
Bro, I encountered the same problem, how did you solve it?

**Comment by loserhou** [comment]
弄好了，但我没做下去所以给扔了，具体原因忘了，但就是环境配置的问题，按照readme仔细配置就行，祝好运






| |
侯业飞
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/4/2024 17:05 |
| To | ***@***.***> |
| Cc | ***@***.***>,
State ***@***.***> |
| Subject | Re: [yinjunbo/IS-Fusion] About Dataset (Issue #19) |

Bro, I encountered the same problem, how did you solve it?
