### ISSUE TITLE
关于 nuscenes_infos_test_mono3d.coco.json

### ISSUE THREAD

**Issue by loserhou** [yinjunbo/IS-Fusion#20]
![849339610b80209f4b0bcd5cb75911c](https://github.com/user-attachments/assets/71ffa695-377a-44d0-8250-927492eb9883)
您好！请问为什么nuscenes_infos_test_mono3d.coco.json只需要生成test的而把train和val的注释掉了？

**Comment by yinjunbo** [comment]
test的也可以注释掉，mono3d的注释应该没有在本工作中用到
