### ISSUE TITLE
关于训练以及测试的GPU数

### ISSUE THREAD

**Issue by loserhou** [yinjunbo/IS-Fusion#21]
我只有四卡，训练的时候把config中的gpu_ids = range(0, 8)改成range(0, 4)
以及run_nus.sh中的CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7改成CUDA_VISIBLE_DEVICES=0,1,2,3 
这样是正确的吗？还有测试的时候怎么修改GPU数呢？
打扰您了，希望得到解答

**Comment by rubbish001** [comment]
看我的项目，https://github.com/rubbish001/Co-Fix3d 吊打这篇

**Comment by loserhou** [comment]
给代码老哥






| |
侯业飞
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月24日 23:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [yinjunbo/IS-Fusion] 关于训练以及测试的GPU数 (Issue #21) |

看我的项目，https://github.com/rubbish001/Co-Fix3d 吊打这篇

**Comment by rubbish001** [comment]
co-fix3d投的是NIPS 中稿就开源，co-fusion准备投aaai，也是中稿就开源

**Comment by rubbish001** [comment]
我是想超越sparseLIF，他是13帧玩的，我目前是单帧图像，刷赢他就完美了

**Comment by loserhou** [comment]
可以加老哥一个微信吗？








| |
侯业飞
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月24日 23:51 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [yinjunbo/IS-Fusion] 关于训练以及测试的GPU数 (Issue #21) |

我是想超越sparseLIF，他是13帧玩的，我目前是单帧图像，刷赢他就完美了

**Comment by rubbish001** [comment]
有卡吗？

**Comment by loserhou** [comment]
用的是学校的平台








| |
侯业飞
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月24日 23:53 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [yinjunbo/IS-Fusion] 关于训练以及测试的GPU数 (Issue #21) |

有卡吗？

**Comment by rubbish001** [comment]
羡慕你们这些有卡的

**Comment by loserhou** [comment]
加个微信老哥






| |
侯业飞
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月24日 23:54 |
| 收件人 | ***@***.***> |
| 主题 | 回复： [yinjunbo/IS-Fusion] 关于训练以及测试的GPU数 (Issue #21) |
用的是学校的平台








| |
侯业飞
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月24日 23:53 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [yinjunbo/IS-Fusion] 关于训练以及测试的GPU数 (Issue #21) |

有卡吗？

**Comment by rubbish001** [comment]
我还一篇文章都没有，等我中了一篇在说吧

**Comment by loserhou** [comment]
包拿下的






| |
侯业飞
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年7月25日 00:02 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
State ***@***.***> |
| 主题 | Re: [yinjunbo/IS-Fusion] 关于训练以及测试的GPU数 (Issue #21) |

我还一篇文章都没有，等我中了一篇在说吧
