### ISSUE TITLE
about lr

### ISSUE THREAD

**Issue by loserhou** [yinjunbo/IS-Fusion#22]
![4840ffc87f234ade42050b934ba0030](https://github.com/user-attachments/assets/17b0fd61-1bac-4b22-90a5-9d3d7007314b)
config中lr为0.0001和您文章里提到的0.001不一致，请问应该使用哪个lr？

**Comment by yinjunbo** [comment]
你好，0.0001是warm up的起始学习率，0.001是稳定后的学习率，可以查看tensorboard来观测lr变化
