### ISSUE TITLE
NCCL ERROR

### ISSUE THREAD

**Issue by Lytang2024** [yinjunbo/IS-Fusion#23]
在运行`bash tools/run-nus.sh extra-tag`时报错
`RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729047590/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    work = _default_pg.barrier()
    RuntimeErrorwork = _default_pg.barrier(): 
NCCL error in: /opt/conda/conda-bld/pytorch_1603729047590/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729047590/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729047590/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729047590/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729047590/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1603729047590/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dell/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dell/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/dell/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dell/anaconda3/envs/open-mmlab/bin/python', '-u', 'tools/train.py', '--local_rank=7', '--launcher', 'pytorch', 'configs/isfusion/isfusion_0075voxel.py', '--extra_tag', 'extra-tag']' returned non-zero exit status 1.
`
查询过后可能时GPU的数量设置的与本机不匹配，请问默认使用的GPU数量是几个，如何配置GPU数量
![屏幕截图 2024-07-27 222520](https://github.com/user-attachments/assets/1fce0748-a3a7-4a1d-bf35-935556521569)

**Comment by yinjunbo** [comment]
默认GPU数量为8，如果不匹配请修改脚本里的CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7和--nproc_per_node=8
