### ISSUE TITLE
Pretrained IS-Fusion

### ISSUE THREAD

**Issue by Zsyyyyyyyy** [yinjunbo/IS-Fusion#24]
请问Pretrained IS-Fusion 的文件该放置在哪里，使用什么命令运行它进行测试

**Comment by rrrrrrrrrice** [comment]
您好 请问您测试跑通了吗 我只想进行测试 不想进行训练 这两个checkpoint对应哪些参数 我看代码只有一个checkpoint路径

**Comment by yinjunbo** [comment]
Hi, you can use this command to test the pretrained model:
`bash tools/dist_test.sh configs/isfusion/isfusion_0075voxel.py path_to_ckpt_directory 1 --eval bbox`, where 1 is the gpu number.
