### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by rrrrrrrrrice** [yinjunbo/IS-Fusion#25]
您好 我阅读了您的论文和部分代码 在您论文和代码中只对nuscenes数据集进行了相关说明和处理 请问在data_preparation.md文件中提到的kitti waymo lyft s3dis scannet sunrgbd数据集您有测试吗？完整的nuscenes数据集对我来说太大了

**Comment by yinjunbo** [comment]
The model is mainly evaluated on the nuScenes dataset. You may need to manually downsample the nuScenes dataset if required.
