### ISSUE TITLE
你的图像融合的时候怎么训练的

### ISSUE THREAD

**Issue by rubbish001** [yinjunbo/IS-Fusion#3]
最后的的图像融合，点云和图像的梯度都打开的吗，采样 one -circle方式吗，训练6轮CBGS还是采样的10轮无CBGS，我就4卡的机器，能给点提示好吗。

**Comment by yinjunbo** [comment]
你好，图像部分需要梯度冻住，具体参见代码，建议使用8卡机器训练以复现精度。

**Comment by rubbish001** [comment]
点云已经超过了focalformer，但是融合val跑了70.7mAP，test只有71.2，,10e不要cbgs的训练方式是最好的吗

**Comment by rubbish001** [comment]
如果你们审稿遇到Co-fix3d，accept啊，效果应该是超过了你们的
