### ISSUE TITLE
Missing multi_scale_deformable_attn_function Module in Middle Encoders

### ISSUE THREAD

**Issue by yqin-falling-stars** [yinjunbo/IS-Fusion#4]
<img width="726" alt="image" src="https://github.com/yinjunbo/IS-Fusion/assets/44614369/c7cda7b8-67a2-4a09-9cd9-f203f8638f45">
<img width="753" alt="image" src="https://github.com/yinjunbo/IS-Fusion/assets/44614369/91fb7538-1a53-4607-86a3-2de9d56d7437">

Issue Description:
Hi there, thank you for your exceptional code implementation. However, I've encountered an issue regarding the absence of the multi_scale_deformable_attn_function module within the middle encoders. This module should ideally include MultiScaleDeformableAttnFunction_fp32 and ms_deform_attn_core_pytorch, which are crucial for running and reproducing the performance reported in the article. This missing module significantly hampers the ability to achieve the expected results and needs to be addressed for effective utilization of the codebase.

**Comment by yinjunbo** [comment]
The missing file has been updated. Thanks for pointing it out.
