### ISSUE TITLE
Hierarchical Scene Fusion vs LSS

### ISSUE THREAD

**Issue by rubbish001** [yinjunbo/IS-Fusion#5]
你这个对比LSS提升了多少，我用的LSS比较low，你这个采用地站多少显存，24g的能跑吗

**Comment by rubbish001** [comment]
我用res50+LSS融合刷到了72.3，准备再搞一篇

**Comment by yinjunbo** [comment]
没有跑过LSS，IS-FUSION需要至少8卡32G机器配置
